version: "3"

services:
  spark-master:
    image: bigdata/spark:2_3_2
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./spark/master:/conf
      - ./data:/tmp/data
    networks:
      - spark-net

  spark-worker-1:
    image: bigdata/spark:2_3_2
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    depends_on:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./spark/worker:/conf
      - ./data:/tmp/data
    networks:
      - spark-net


  zeppelin:
    image: bigdata/zeppelin:0_8_0
    container_name: zeppelin
    command: bin/zeppelin.sh
    hostname: zeppelin
    ports:
      - 80:8080
    volumes:
      - ./zeppelin/notebook:/opt/zeppelin/notebook
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      MASTER: "spark://spark-master:7077"
    depends_on:
      - spark-master
    networks:
      - spark-net

networks:
  spark-net:
    external:
      name: spark-net